apiVersion: v2
name: audicia-operator
description: Automated RBAC policy generation for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"
kubeVersion: ">=1.27.0-0"
home: https://audicia.io
sources:
  - https://github.com/felixnotka/audicia
keywords:
  - kubernetes
  - rbac
  - security
  - audit
  - operator
  - policy
maintainers:
  - name: Felix Notka
    url: https://github.com/felixnotka
